openapi: "3.0.0"
info:
  title: Voicemail API
  description: Manage voicemail recordings.
  version: 1.0.0
servers:
  - url: /api/voicemails
paths:
  /:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  transcript:
                    type: string
  /{vm_id}:
    patch:
      parameters:
        - in: path
          name: vm_id
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                read:
                  type: boolean
      responses:
        204:
          description: Successfully updated
        400:
          description: Invalid input
        404:
          description: Not found
    delete:
      parameters:
        - in: path
          name: vm_id
          required: true
          schema:
            type: integer
      responses:
        204:
          description: Successfully deleted
        404:
          description: Not found
