--- 
jobs: 
  test: 
    env: 
      PGHOST: localhost
      PGPASSWORD: postgres
      PGPORT: 5432
      PGUSER: postgres
      POSTGRES_DB: temp_db
    runs-on: ubuntu-latest
    services: 
      postgres: 
        env: 
          POSTGRES_PASSWORD: postgres
        image: postgres
        options: "--health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5"
        ports: 
          - "5432:5432"
    steps: 
      - 
        name: "Checkout code"
        uses: actions/checkout@v2
      - 
        name: "Set up Node.js"
        uses: actions/setup-node@v1
        with: 
          node-version: 14.x
      - 
        name: "npm install and test"
        run: |-
            npm install
            npm test
name: "Node Github CI"
true: 
  push: 
    branches: 
      - main
      - develop
